import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: { padding: 30, fontSize: 11, fontFamily: 'Helvetica' },
  title: { fontSize: 20, marginBottom: 4, fontWeight: 'bold' },
  subtitle: { fontSize: 10, color: '#666', marginBottom: 20 },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 13, fontWeight: 'bold', marginBottom: 6, borderBottom: 1, paddingBottom: 4 },
  row: { fontSize: 10, marginBottom: 3 },
  summaryText: { fontSize: 10, lineHeight: 1.5, marginBottom: 6 },
  priorityBox: { fontSize: 10, backgroundColor: '#f3f4f6', padding: 8, borderRadius: 4 },
  issueBox: { marginBottom: 8, padding: 8, borderRadius: 4, borderLeft: 3 },
  issueCritical: { backgroundColor: '#fef2f2', borderLeftColor: '#dc2626' },
  issueMedium: { backgroundColor: '#fffbeb', borderLeftColor: '#d97706' },
  issueLow: { backgroundColor: '#eff6ff', borderLeftColor: '#2563eb' },
  issueHeader: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 3 },
  issueType: { fontSize: 10, fontWeight: 'bold' },
  issueSeverity: { fontSize: 8, fontWeight: 'bold' },
  issueDesc: { fontSize: 9, color: '#333' },
  issueLocation: { fontSize: 8, color: '#666', marginTop: 2 },
  footer: { position: 'absolute', bottom: 20, left: 30, right: 30, fontSize: 8, color: '#999', textAlign: 'center' },
});

interface ScanData {
  buttons: string[];
  links: string[];
  formsCount: number;
  inputsCount: number;
  consoleErrors: string[];
  networkErrors: { url: string; status: number | string }[];
}

interface Issue {
  type: string;
  description: string;
  severity: 'critical' | 'medium' | 'low';
  location?: string;
}

interface Analysis {
  summary: string;
  priorityFix: string;
  issues: Issue[];
}

interface ReportProps {
  url: string;
  scanDate: string;
  analysis: Analysis;
  scanData: ScanData;
}

const severityOrder: Record<string, number> = { critical: 0, medium: 1, low: 2 };
const issueStyleMap: Record<string, any> = {
  critical: styles.issueCritical,
  medium: styles.issueMedium,
  low: styles.issueLow,
};

export function ReportDocument({ url, scanDate, analysis, scanData }: ReportProps) {
  const issues = analysis?.issues || [];
  const sortedIssues = [...issues].sort(
    (a, b) => severityOrder[a.severity] - severityOrder[b.severity]
  );

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.title}>Krato QA Report</Text>
        <Text style={styles.subtitle}>{url} - Scanned {scanDate}</Text>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Summary</Text>
          <Text style={styles.row}>Buttons found: {scanData.buttons.length}</Text>
          <Text style={styles.row}>Links found: {scanData.links.length}</Text>
          <Text style={styles.row}>Forms found: {scanData.formsCount}</Text>
          <Text style={styles.row}>Inputs found: {scanData.inputsCount}</Text>
          <Text style={styles.row}>Console errors: {scanData.consoleErrors.length}</Text>
          <Text style={styles.row}>Network errors: {scanData.networkErrors.length}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>AI Analysis</Text>
          <Text style={styles.summaryText}>{analysis?.summary}</Text>
          {analysis?.priorityFix && (
            <Text style={styles.priorityBox}>Fix this first: {analysis.priorityFix}</Text>
          )}
        </View>

        {sortedIssues.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Issues ({sortedIssues.length})</Text>
            {sortedIssues.map((issue, i) => (
              <View key={i} style={[styles.issueBox, issueStyleMap[issue.severity]]}>
                <View style={styles.issueHeader}>
                  <Text style={styles.issueType}>{issue.type}</Text>
                  <Text style={styles.issueSeverity}>{issue.severity.toUpperCase()}</Text>
                </View>
                <Text style={styles.issueDesc}>{issue.description}</Text>
                {issue.location && (
                  <Text style={styles.issueLocation}>Location: {issue.location}</Text>
                )}
              </View>
            ))}
          </View>
        )}

        <Text style={styles.footer}>Generated by Krato - kratoai.vercel.app</Text>
      </Page>
    </Document>
  );
}